applicationName: reviews-app-backend
replicaCount: 1
image:
  repo: 975050202573.dkr.ecr.us-east-1.amazonaws.com/reviews-app-backend
  tag: 0.1
port: 3000
servicePort: 80
secretName: mysql-secret
appConfig:
  envVars:
  - name: DB_ENDPOINT
    value: mysql
  secrets:
  - env_name: DB_USERNAME
    secretName: mysql-secret
    secretKeyName: MYSQL_USER
  - env_name: DB_PASSWORD
    secretName: mysql-secret
    secretKeyName: MYSQL_PASSWORD
  - env_name: DB_NAME
    secretName: mysql-secret
    secretKeyName: MYSQL_DATABASE